config/routes.rb
Rails.application.routes.draw do
  resources :mailsignatures
  get 'home/index'
  #root to: 'home#index'
  root to: 'mailsignatures#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mailsignature.rb
class Mailsignature < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :mailsignature
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/mailsignatures_controller.rb
class MailsignaturesController < ApplicationController
  before_action :set_mailsignature, only: [:show, :edit, :update, :destroy]

  # GET /mailsignatures
  # GET /mailsignatures.json
  def index
    @mailsignature = current_user.mailsignature
  end

  # GET /mailsignatures/1
  # GET /mailsignatures/1.json
  def show
  end

  # GET /mailsignatures/new
  def new
    @mailsignature = Mailsignature.new
  end

  # GET /mailsignatures/1/edit
  def edit
  end

  # POST /mailsignatures
  # POST /mailsignatures.json
  def create
    @mailsignature = Mailsignature.new(mailsignature_params)
    @mailsignature.user=current_user
    respond_to do |format|
      if @mailsignature.save
        format.html { redirect_to mailsignatures_url, notice: 'Mailsignature was successfully created.' }
        format.json { render :show, status: :created, location: @mailsignature }
      else
        format.html { render :new }
        format.json { render json: @mailsignature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mailsignatures/1
  # PATCH/PUT /mailsignatures/1.json
  def update
    respond_to do |format|
      if @mailsignature.update(mailsignature_params)
        format.html { redirect_to mailsignatures_url, notice: 'Mailsignature was successfully updated.' }
        format.json { render :show, status: :ok, location: @mailsignature }
      else
        format.html { render :edit }
        format.json { render json: @mailsignature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mailsignatures/1
  # DELETE /mailsignatures/1.json
  def destroy
    @mailsignature.destroy
    respond_to do |format|
      format.html { redirect_to mailsignatures_url, notice: 'Mailsignature was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mailsignature
      @mailsignature = Mailsignature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mailsignature_params
      params.require(:mailsignature).permit(:name, :saludation, :mobilespain, :msvisible, :mobilefrance, :mfvisible, :mobilegermany, :mgvisible, :skype, :skypevisible,:facebook, :twitter, :banner, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mailsignatures_helper.rb
module MailsignaturesHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Signatures</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mailsignatures/_form.html.haml
= form_for(mailsignature) do |f|
  - if mailsignature.errors.any?
    #error_explanation
      %h2
        = pluralize(mailsignature.errors.count, "error")
        prohibited this mailsignature from being saved:
      %ul
        - mailsignature.errors.full_messages.each do |message|
          %li= message
  .field
    %h3 banners

    %h4 #1 (default)
    =image_tag 'banner1.jpg'
    %h4 #2
    =image_tag 'banner2.jpg'


  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :saludation
    = f.text_field :saludation
  .field
    = f.label :mobilespain
    = f.text_field :mobilespain
    = f.check_box :msvisible
  .field
    = f.label :mobilefrance
    = f.text_field :mobilefrance
    = f.check_box :mfvisible
  .field
    = f.label :mobilegermany
    = f.text_field :mobilegermany

    = f.check_box :mgvisible
  .field
    = f.label :skype
    = f.text_field :skype
    = f.check_box :skypevisible
  .field

    = f.label :banner
    = f.number_field :banner

  .actions
    = f.submit

app/views/mailsignatures/edit.html.haml
%h1 Editing Mailsignature
= render 'form', mailsignature: @mailsignature
= link_to 'Back', mailsignatures_path

app/views/mailsignatures/new.html.haml
%h1 New Mailsignature
= render 'form', mailsignature: @mailsignature
= link_to 'Back', mailsignatures_path